hamji/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

import polls.views

from . import views

router = routers.DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"questions", polls.views.QuestionViewSet)

urlpatterns = [
    path("_api/", include(router.urls)),
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/suggest-choice/', views.ChoiceCreateView.as_view(), name='new-choice'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('like/<int:pk>', views.LikeView, name='like_question'),

    #path('<int:pk>/approve-choice/', views.ApprovedChoiceUpdateView.as_view(), name='approve_choice'),

]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import User


class QuestionManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            lookup = (Q(question_text__icontains=query))
            qs = qs.filter(lookup).distinct()
        return qs

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date      = models.DateTimeField("date published")
    is_closed     = models.BooleanField(default=False)
    closed_at     = models.DateField(default=datetime.date.today, auto_now=False, auto_now_add=False)
    likes         = models.ManyToManyField(User, related_name='question_likes')
    owner         = models.ForeignKey(User, on_delete=models.CASCADE, related_name='question_owner')

    objects       = QuestionManager()

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)




class ChoiceManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            lookup =  (Q(choice_text__icontains=query))
            qs = qs.filter(lookup).distinct()
        return qs


class Choice(models.Model):
    question     = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text  = models.CharField(max_length=200)
    votes        = models.IntegerField(default=0)

    objects      = ChoiceManager()

    def __str__(self):
        return self.choice_text


class SuggestedChoice(models.Model):
    question       = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text    = models.CharField(max_length=200)
    is_approved    = models.BooleanField(default=False)
    created_date   = models.DateField(default=datetime.date.today)

    def __str__(self):
        return str(self.question) + ' | ' + str(self.choice_text)


class Comment(models.Model):
    question       = models.ForeignKey(Question, related_name="comment", on_delete=models.CASCADE) # related_name="comment",
    author         = models.CharField(max_length=20)
    body           = models.TextField(max_length=300)
    created_date  = models.DateTimeField(auto_now_add=True)
    #author can become user but not yet, self FK for replying comments

    def __str__(self):
        return str(self.question)

polls/forms.py
from django import forms
from .models import Choice, Question, SuggestedChoice, Comment


class SuggestChoiceForm(forms.ModelForm):
    class Meta:
        model = SuggestedChoice
        #fields = '__all__'
        fields = ('choice_text',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'body')


class ApprovedChoiceForm(forms.ModelForm):
    class Meta:
        model = SuggestedChoice
        fields = '__all__'
        # fields = ('is_approved',)

polls/views.py
import requests
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from rest_framework import viewsets
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from itertools import chain

from utils.url import restify

from .models import Choice, Question, SuggestedChoice, Comment
from .serializers import QuestionSerializer
from .forms import SuggestChoiceForm, CommentForm, ApprovedChoiceForm

"""original listview"""
# class IndexView(generic.ListView):
#     template_name = "polls/index.html"
#     context_object_name = "latest_question_list"
#     allow_empty = False
#     queryset = Question.objects.filter(is_closed=False)
#
#     # def get_queryset(self):
#     #     """Return the last five published questions."""
#     #     response = requests.get(restify("/polls/"))
#     #     questions = response.json()
#     #     return questions[:5]

class IndexView(generic.ListView):
    template_name = "polls/indexview.html"
    count = 0
    allow_empty = False

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['count'] = self.count or 0
        context['query'] = self.request.GET.get('q')

        return context

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        object_list = Question.objects.filter(is_closed=False)

        if query:
            if len(query) > 1:
                question_results = Question.objects.search(query)
                choice_results = Choice.objects.search(query)

                queryset_chain = chain(
                                question_results,
                                choice_results
                )
                qs = sorted(queryset_chain,
                            key=lambda instance: instance.pk,
                            reverse=True)
                self.count = len(qs)
                return qs
            else:
                messages.error(self.request, 'Please type more than two characters')
        return object_list



class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


def LikeView(request, pk):
    question = get_object_or_404(Question, id=request.POST.get('question_id'))
    #template button "name" is question_id
    question.likes.add(request.user)
    return HttpResponseRedirect(reverse('detail', args=[str(pk]))


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        #selected_choice.votes += 1
        selected_choice.votes = F('votes')+1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

from django.urls import reverse_lazy

class ChoiceCreateView(generic.CreateView):
    model = SuggestedChoice
    template_name =  "polls/suggestedchoice_form.html"
    form_class = SuggestChoiceForm


    def is_limit_reached(self):
        return SuggestedChoice.objects.all().count() >= 3


    def post(self, request, *args, **kwargs):
        if self.is_limit_reached():
            print('limit over')
            messages.info(request, 'Warning: You have reached the limit for the number of suggestions you can create at this time.')
            return HttpResponseRedirect(reverse('polls:index'))
        else:
            return super().post(request, *args, **kwargs)


    def form_valid(self, form):
        form.instance.question_id = self.kwargs['pk']
        # form.instance.question_id = self.kwargs['question_id']
        return super().form_valid(form)


    def get_success_url(self):
        return reverse_lazy('polls:detail', kwargs={'pk': self.kwargs['pk']})


class AddCommentView(generic.CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'polls/add_comment.html'
    #fields = '__all__'

    def form_valid(self, form):
        form.instance.question_id = self.kwargs['pk']
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('polls:detail', kwargs={'pk': self.kwargs['pk']})


# FIX NEEDED
# class ApprovedChoiceUpdateView(generic.UpdateView):
#     model = SuggestedChoice
#     template_name =  "polls/approve_choice.html"
#     form_class = ApprovedChoiceForm
#
#
#     def form_valid(self, form):
#         form.instance.question_id = self.kwargs['pk']
#         return super().form_valid(form)
#
#
#     def get_success_url(self):
#         return reverse_lazy('polls:detail', kwargs={'pk': self.kwargs['pk']})


# API
# ===


class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

polls/templates/polls/add_comment.html
{% extends './base.html' %}

{% block content %}

<h1> Add Comment  </h1>
<br/>

<div class="form-group">
    <form method="POST">
        {% csrf_token %}
   {% if user.is_authenticated %}
        {{ form.media }}
   {% endif %}
        {{ form.as_p }}
        <br/>
        <button class="btn btn-secondary"> Add Comment </button>
    </form>
</div>

<!-- <script>
    var name = "{{ user.username }}";
    document.getElementById("users_id").value
             = name;

</script> -->

{% endblock %}

polls/templates/polls/approve_choice.html
{% extends './base.html' %}

{% block content %}

<div class="container-fluid">
<br><br><br>
<div class="row">

    <div class="col-md-6">
    </div>
</div>

<div class="row justify-content-md-center">
    <div class="col-md-6">
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
{% for f in form %}
{{f}}
{% endfor %}
                <br/>
                <button class="btn"> Suggest choice </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Polls</title>
    <meta charset="UTF-8">
</head>
<body>
   <div id="warp">
        <div id="header">
        </div>
        <div id="content">
            <h1><a href="{% url 'polls:index' %}"> Polls </a></h1>
              <div class="container">
                {% block content %}
                {% endblock content %}
                <br><br>
              </div>
        </div>
    </div>
</body>
</html>

polls/templates/polls/choice_form.html
{% extends './base.html' %}

{% block content %}

{{ pk }}
<div class="container-fluid">
<br><br><br>
<div class="row">

    <div class="col-md-6">
    </div>
</div>

<div class="row justify-content-md-center">
    <div class="col-md-6">
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
           {% if user.is_authenticated %}
                {{ form.media }}
                {{ form.as_p }}
           {% else %}
                 {{ form.as_p }}
           {% endif %}
                <br/>
                <button class="btn btn-secondary"> Add choice </button>
            </form>
        </div>
    </div>
</div>

    <script>
        var name = "Anonymous User";
        document.getElementById("users_id").value
                 = name;

    </script>


{% endblock %}

polls/templates/polls/detail.html
{% extends './base.html' %}

    <div class="container">
        <h1>Detail</h1>
    </div>

{% block content %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

<!-- like button -->
<form action="{% url 'polls:like_question' question.pk %}" method="POST">
  {% csrf_token %}
<button type="submit", name="question_id", value="{{ question.id}}, ">Like</button>

<br>



<div class="btn_suggest">
    <a href="{% url 'polls:new-choice' question.pk %}"> Suggest new choices for question: "{{ question.question_text }}"</a>
</div>
<br>
<br>

<!--Comment-->
<hr>

<h2>Comment</h2>
<a href="{% url 'polls:add_comment' question.pk %}"> Add Comment </a>
    <ul class="list-group list-group-flush">
        <li class="list-group-item ">
          {% if not question.comment.all %}
              No Comments yet...

          {% else %}

        {% for comment in question.comment.all %}
            <strong>{{ comment.author }} - {{ comment.created_date }}</strong>
            <br>
            {{ comment.body }}
            <br><br><hr style="width: 100%;">
        {% endfor %}
         </li>
        {% endif %}
    </ul>

<!--Comment-->




{% endblock content %}

polls/templates/polls/index.html
{% extends './base.html' %}
{% block content %}

<!-- login, logout button starts -->
{% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page"
            href="{% url 'logout' %}">Logout</a>
          </li>

{% else %}

          <li class="nav-item">
            <a class="nav-link active" aria-current="page"
            href="{% url 'login' %}">Login</a>
          </li>

{% endif %}

<!-- login, logout button ends -->


<!-- list starts -->
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href={% url 'polls:detail' question.id %}>{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<!-- list ends -->


{% endblock content %}

polls/templates/polls/indexview.html
{% extends './base.html' %}
{% load class_name %}
{% block content %}
<!-- login, logout button starts -->
{% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page"
            href="{% url 'logout' %}">Logout</a>
          </li>

{% else %}

          <li class="nav-item">
            <a class="nav-link active" aria-current="page"
            href="{% url 'login' %}">Login</a>
          </li>

{% endif %}
<br>
<!-- login, logout button ends -->


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}



<fieldset>
{% if query %}
<legend>
    <h3>{{ count }} results for <b>{{ query }}</b></h3></legend>
{% else %}
  <legend>  <h3><b>List of questions</b></h3>
{% endif %}
</legend>


<!-- list starts -->

<!-- list ends -->


<!-- Search starts -->
<div class='row title-row my-5'>

{% if object_list %}
  {% for object in object_list %}
      {% with object|class_name as klass %}
        {% if klass == 'Question' %}
             <div class='row'>
               <div class='col-12'>
                <li>  <a href={% url 'polls:detail' object.id %}>{{ object.question_text }}</a> </li>
              </div>
            </div>

        {% elif klass == 'Choice' %}
             <div class='row'>
               <div class='col-12'>
                <li> <span> {{ object.choice_text }}</span> <a href={% url 'polls:detail' object.question.id %}>link</a> </li>
                </div>
              </div>

        {% else %}
          <li><a href={% url 'polls:detail' question.id %}>{{ question.question_text }}</a></li>

        {% endif %}
      {% endwith %}
  {% endfor %}

{% else %}
  {% if query %}
  No match
  {% else %}
  No polls are available.
  {% endif %}

{% endif %}
</fieldset>
<!-- Search ends -->

<div class='row'>
    <div class='col-12 col-md-6 mx-auto my-5 py-5'>
    <form method='GET' class='' action='.'>

        <div class="input-group form-group-no-border mx-auto" style="margin-bottom: 0px; font-size: 32px;">
            <span class="input-group-addon cfe-nav" style='color:#000'>
                <i class="fa fa-search" aria-hidden="true"></i>
            </span>
            <input type="text" name="q" data-toggle="popover" data-placement="bottom" data-content="Press enter to search" class="form-control cfe-nav mt-0 py-3" placeholder="Press enter to search" value="" style="" data-original-title="" title="" autofocus="autofocus">
        </div>

    </form>

    </div>
</div>


{% endblock content %}

polls/templates/polls/old_choice_form.html
{% extends './base.html' %}

    <div class="container">
        <h1>Suggestion for new choices</h1>
    </div>

{% block content %}



{{ choice.votes}}
{% for obj in object_list %}
 {{ obj }}
{% endfor %}
{{ choice }}
{{ choice.question_id }}


 {{polls_choice.question_id}}
 {{polls_choice.question_id}}
 {{choice.id_question}}

 {{ polls_choice.votes }}
{{ polls_choice.question_id }}

{{ choice.pk}}
    <h2> Suggest a New Choice " {{ choice }} "</h2>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="editor">
                <p>{{form}}</p>
            </div>
            <div class="submit">

                <input type="submit" value="post">
            </div>
        </form>

    <div class="btn_back">
        <a href="{% url 'polls:index' %}" >Return to question list</a>
    </div>


<script>
    const id = "{{ choice.question_id }}";
    document.getElementById("question_id").value
             = id;
</script>



{% endblock content %}

polls/templates/polls/results.html
{% extends './base.html' %}

    <div class="container">
        <h1>Suggestion for new choices</h1>
    </div>

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}

polls/templates/polls/suggestedchoice_form.html
{% extends './base.html' %}

{% block content %}

<div class="container-fluid">
<br><br><br>
<div class="row">

    <div class="col-md-6">
    </div>
</div>

<div class="row justify-content-md-center">
    <div class="col-md-6">
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                 {{ form.as_p }}
                <br/>
                <button class="btn"> Suggest choice </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}